var searchData=
[
  ['data_20types_0',['Data Types',['../group__usbd__data__types.html',1,'Data Types'],['../group__usbh__data__types.html',1,'Data Types']]],
  ['debug_1',['Debug',['../usb_migration.html#autotoc_md21',1,'']]],
  ['debug_20events_2',['Debug Events',['../group__usbd__evr.html',1,'Debug Events'],['../group__usbh__evr.html',1,'Debug Events']]],
  ['debugging_3',['Debugging',['../usbd_create_app.html#usbd_debugging',1,'Debugging'],['../usbh_create_app.html#usbh_debugging',1,'Debugging']]],
  ['default_20usb_20descriptors_4',['Changing Default USB Descriptors',['../usbd_create_app.html#Overriding_Descriptors',1,'']]],
  ['descriptor_5',['Descriptor',['../USB_Concepts.html#USB_Configuration_Descriptor',1,'Configuration Descriptor'],['../USB_Concepts.html#USB_Device_Descriptor',1,'Device Descriptor'],['../USB_Concepts.html#USB_Device_Qualifier_Descriptor',1,'Device Qualifier Descriptor'],['../USB_Concepts.html#USB_Endpoint_Descriptor',1,'Endpoint Descriptor'],['../USB_Concepts.html#USB_Interface_Descriptor',1,'Interface Descriptor']]],
  ['descriptors_6',['Descriptors',['../usbd_create_app.html#Overriding_Descriptors',1,'Changing Default USB Descriptors'],['../USB_Concepts.html#USB_String_Descriptor',1,'String Descriptors'],['../USB_Concepts.html#USB_Descriptors',1,'USB Descriptors'],['../USB_Classes.html#CDC_Descriptors',1,'USB Descriptors'],['../USB_Classes.html#HID_Descriptors',1,'USB Descriptors'],['../USB_Classes.html#MSC_Descriptors',1,'USB Descriptors'],['../USB_Classes.html#CustomClass_Descriptors',1,'USB Descriptors']]],
  ['device_7',['Device',['../group__usbd.html',1,'USB Device'],['../USB_Device.html',1,'USB Device'],['../function_overview.html#usbd_functions',1,'USB Device'],['../usb_migration.html#autotoc_md22',1,'USB Device']]],
  ['device_20class_8',['Device Class',['../group__usbd__adcFunctions.html',1,'ADC: Audio Device Class'],['../USB_Classes.html#ADC',1,'ADC: Audio Device Class'],['../USB_Classes.html#CDC',1,'CDC: Communication Device Class'],['../group__usbd__DevClassFunctions.html',1,'Device Class'],['../group__usbh__DevClassFunctions.html',1,'Device Class'],['../group__usbh__hidFunctions.html',1,'HID: Human Interface Device Class'],['../USB_Classes.html#HID',1,'HID: Human Interface Device Class'],['../USB_Classes.html#CustomClass_Device',1,'USB Device implementing any Device Class'],['../USB_Classes.html#CustomClass_Host',1,'USB Host supporting any Device Class']]],
  ['device_20class_20abstract_20control_20model_9',['CDC (ACM): Communication Device Class (Abstract Control Model)',['../group__usbh__cdcacmFunctions.html',1,'']]],
  ['device_20class_20acm_10',['CDC: Communication Device Class (ACM)',['../group__usbd__cdcFunctions__acm.html',1,'']]],
  ['device_20class_20acm_20functions_11',['USBH_CDC_ACM: Communication Device Class ACM Functions',['../group__usbh__evr__cdc__acm__func.html',1,'']]],
  ['device_20class_20configuration_20and_20usb_20endpoint_20settings_12',['USB Device Class Configuration and USB Endpoint Settings',['../usbd_create_app.html#USB_Device_Class_Configuration',1,'']]],
  ['device_20class_20functions_13',['Device Class Functions',['../group__usbd__evr__adc__func.html',1,'USBD_ADC: Audio Device Class Functions'],['../group__usbd__evr__cdc__func.html',1,'USBD_CDC: Communication Device Class Functions']]],
  ['device_20class_20ncm_14',['CDC: Communication Device Class (NCM)',['../group__usbd__cdcFunctions__ncm.html',1,'']]],
  ['device_20configuration_15',['USB Device Configuration',['../usbd_create_app.html#USB_Device_Configuration',1,'']]],
  ['device_20descriptor_16',['Device Descriptor',['../USB_Concepts.html#USB_Device_Descriptor',1,'']]],
  ['device_20functions_17',['Device Functions',['../group__usbd__evr__hid__func.html',1,'USBD_HID: Human Interface Device Functions'],['../group__usbh__evr__hid__func.html',1,'USBH_HID: Human Interface Device Functions'],['../group__usbh__evr__msc__func.html',1,'USBH_MSC: Mass Storage Device Functions']]],
  ['device_20hid_18',['USB Device HID',['../usbd_example_hid.html',1,'usbd_examples']]],
  ['device_20implementing_20any_20device_20class_19',['USB Device implementing any Device Class',['../USB_Classes.html#CustomClass_Device',1,'']]],
  ['device_20mass_20storage_20',['USB Device Mass Storage',['../usbd_example_msc.html',1,'usbd_examples']]],
  ['device_20qualifier_20descriptor_21',['Device Qualifier Descriptor',['../USB_Concepts.html#USB_Device_Qualifier_Descriptor',1,'']]],
  ['device_20resource_20requirements_22',['USB Device Resource Requirements',['../resource_requirements.html#usbd_res_req',1,'']]],
  ['device_20threads_20and_20function_20calls_23',['USB Device Threads and Function Calls',['../group__usbd.html#usbd_dev_threads',1,'']]],
  ['device_20virtual_20com_20port_24',['USB Device Virtual COM Port',['../usbd_example_cdc.html',1,'usbd_examples']]],
  ['device_5fdescriptor_25',['device_descriptor',['../group__usbd__data__types.html#a6e7af2b72d956bff4b2e91b2ba82cc10',1,'usbd_desc_t']]],
  ['device_5fqualifier_5ffs_26',['device_qualifier_fs',['../group__usbd__data__types.html#a2ce5f6c6aa524acf601740cf71b13ee5',1,'usbd_desc_t']]],
  ['device_5fqualifier_5fhs_27',['device_qualifier_hs',['../group__usbd__data__types.html#a73b3be3fb9cc929ad18260376e891938',1,'usbd_desc_t']]],
  ['devices_28',['Configuration of Attachable USB Devices',['../usbh_create_app.html#USB_Device_Class_Configuration_USBH',1,'']]],
  ['directories_20and_20files_29',['Directories and Files',['../group__usb__files.html',1,'']]],
  ['documentation_20structure_30',['Documentation Structure',['../index.html#doc_structure',1,'']]],
  ['driver_20and_20controller_31',['Driver and Controller',['../usbd_create_app.html#USB_Driver_Configuration',1,'USB Driver and Controller'],['../usbh_create_app.html#USB_Driver_Configuration_USBH',1,'USB Driver and Controller']]],
  ['driver_20functions_32',['Driver Functions',['../group__usbd__evr__driver__func.html',1,'USBD_Driver: Driver Functions'],['../group__usbh__evr__driver__func.html',1,'USBH_Driver: Driver Functions']]],
  ['dwdterate_33',['dwDTERate',['../group__usbd__data__types.html#a1c7eaa2f09ca8253de1711d01e05e02c',1,'CDC_LINE_CODING']]],
  ['dwntbinmaxsize_34',['dwNtbInMaxSize',['../group__usbd__data__types.html#abc0be89264a968b7b4bb6c1a993b2779',1,'CDC_NCM_NTB_PARAM']]],
  ['dwntboutmaxsize_35',['dwNtbOutMaxSize',['../group__usbd__data__types.html#a1b181550906a4c767bdf49fffbffd658',1,'CDC_NCM_NTB_PARAM']]],
  ['dynamic_20change_36',['Dynamic change',['../usbd_create_app.html#autotoc_md1',1,'']]]
];
