var searchData=
[
  ['calls_0',['USB Device Threads and Function Calls',['../group__usbd.html#usbd_dev_threads',1,'']]],
  ['cdc_20acm_20_3a_20communication_20device_20class_20abstract_20control_20model_1',['CDC (ACM): Communication Device Class (Abstract Control Model)',['../group__usbh__cdcacmFunctions.html',1,'']]],
  ['cdc_20class_20features_2',['CDC Class Features',['../USB_Classes.html#CDC_Features',1,'']]],
  ['cdc_3a_20communication_20device_20class_3',['CDC: Communication Device Class',['../USB_Classes.html#CDC',1,'']]],
  ['cdc_3a_20communication_20device_20class_20acm_4',['CDC: Communication Device Class (ACM)',['../group__usbd__cdcFunctions__acm.html',1,'']]],
  ['cdc_3a_20communication_20device_20class_20ncm_5',['CDC: Communication Device Class (NCM)',['../group__usbd__cdcFunctions__ncm.html',1,'']]],
  ['cdc_5fline_5fcoding_6',['CDC_LINE_CODING',['../group__usbd__data__types.html#structCDC__LINE__CODING',1,'']]],
  ['cdc_5fncm_5fntb_5fparam_7',['CDC_NCM_NTB_PARAM',['../group__usbd__data__types.html#structCDC__NCM__NTB__PARAM',1,'']]],
  ['change_8',['change',['../usbd_create_app.html#autotoc_md1',1,'Dynamic change'],['../usbd_create_app.html#autotoc_md0',1,'Static change']]],
  ['changing_20default_20usb_20descriptors_9',['Changing Default USB Descriptors',['../usbd_create_app.html#Overriding_Descriptors',1,'']]],
  ['class_10',['Class',['../group__usbd__adcFunctions.html',1,'ADC: Audio Device Class'],['../USB_Classes.html#ADC',1,'ADC: Audio Device Class'],['../USB_Classes.html#CDC',1,'CDC: Communication Device Class'],['../group__usbd__classFunctions.html',1,'Custom Class'],['../group__usbh__customFunctions.html',1,'Custom Class'],['../USB_Classes.html#CustomClass',1,'Custom Class'],['../group__usbd__DevClassFunctions.html',1,'Device Class'],['../group__usbh__DevClassFunctions.html',1,'Device Class'],['../group__usbd__hidFunctions.html',1,'HID: Human Interface Class'],['../group__usbh__hidFunctions.html',1,'HID: Human Interface Device Class'],['../USB_Classes.html#HID',1,'HID: Human Interface Device Class'],['../group__usbd__mscFunctions.html',1,'MSC: Mass Storage Class'],['../group__usbh__mscFunctions.html',1,'MSC: Mass Storage Class'],['../USB_Classes.html#MSC',1,'MSC: Mass Storage Class'],['../USB_Classes.html#CustomClass_Device',1,'USB Device implementing any Device Class'],['../USB_Classes.html#CustomClass_Host',1,'USB Host supporting any Device Class']]],
  ['class_20abstract_20control_20model_11',['CDC (ACM): Communication Device Class (Abstract Control Model)',['../group__usbh__cdcacmFunctions.html',1,'']]],
  ['class_20acm_12',['CDC: Communication Device Class (ACM)',['../group__usbd__cdcFunctions__acm.html',1,'']]],
  ['class_20acm_20functions_13',['USBH_CDC_ACM: Communication Device Class ACM Functions',['../group__usbh__evr__cdc__acm__func.html',1,'']]],
  ['class_20configuration_20and_20usb_20endpoint_20settings_14',['USB Device Class Configuration and USB Endpoint Settings',['../usbd_create_app.html#USB_Device_Class_Configuration',1,'']]],
  ['class_20features_15',['Class Features',['../USB_Classes.html#CDC_Features',1,'CDC Class Features'],['../USB_Classes.html#HID_Features',1,'HID Class Features'],['../USB_Classes.html#MSC_Features',1,'MSC Class Features']]],
  ['class_20functions_16',['Class Functions',['../group__usbd__evr__adc__func.html',1,'USBD_ADC: Audio Device Class Functions'],['../group__usbd__evr__cdc__func.html',1,'USBD_CDC: Communication Device Class Functions'],['../group__usbd__evr__cc__func.html',1,'USBD_CustomClass: Custom Class Functions'],['../group__usbd__evr__msc__func.html',1,'USBD_MSC: Mass Storage Class Functions'],['../group__usbh__evr__cc__func.html',1,'USBH_CustomClass: Custom Class Functions']]],
  ['class_20ncm_17',['CDC: Communication Device Class (NCM)',['../group__usbd__cdcFunctions__ncm.html',1,'']]],
  ['classes_18',['Supported USB Classes',['../USB_Classes.html',1,'']]],
  ['client_19',['HID Client',['../usbd_pc_utilities.html#hid_client_app',1,'']]],
  ['cmsis_20rtos2_20requirements_20',['CMSIS RTOS2 Requirements',['../resource_requirements.html#usbd_rtos_req',1,'CMSIS-RTOS2 Requirements'],['../resource_requirements.html#usbh_rtos_req',1,'CMSIS-RTOS2 Requirements']]],
  ['code_21',['Source Code',['../usbd_pc_utilities.html#autotoc_md12',1,'']]],
  ['code_20implementation_22',['Code Implementation',['../usbd_create_app.html#User_Code_Implementation',1,'User Code Implementation'],['../usbh_create_app.html#USBH_User_Code_Implementation',1,'User Code Implementation']]],
  ['code_20templates_23',['User Code Templates',['../group__usbd__classFunctions.html#autotoc_md35',1,'']]],
  ['codes_24',['Status and Error Codes',['../group__status__error__codes__usb.html',1,'']]],
  ['com_20port_25',['USB Device Virtual COM Port',['../usbd_example_cdc.html',1,'usbd_examples']]],
  ['communication_26',['USB Communication',['../USB_Concepts.html#USB_Communication',1,'']]],
  ['communication_20device_20class_27',['CDC: Communication Device Class',['../USB_Classes.html#CDC',1,'']]],
  ['communication_20device_20class_20abstract_20control_20model_28',['CDC (ACM): Communication Device Class (Abstract Control Model)',['../group__usbh__cdcacmFunctions.html',1,'']]],
  ['communication_20device_20class_20acm_29',['CDC: Communication Device Class (ACM)',['../group__usbd__cdcFunctions__acm.html',1,'']]],
  ['communication_20device_20class_20acm_20functions_30',['USBH_CDC_ACM: Communication Device Class ACM Functions',['../group__usbh__evr__cdc__acm__func.html',1,'']]],
  ['communication_20device_20class_20functions_31',['USBD_CDC: Communication Device Class Functions',['../group__usbd__evr__cdc__func.html',1,'']]],
  ['communication_20device_20class_20ncm_32',['CDC: Communication Device Class (NCM)',['../group__usbd__cdcFunctions__ncm.html',1,'']]],
  ['component_20selection_33',['Component Selection',['../usb_migration.html#usb_migration_component',1,'Component Selection'],['../usbd_create_app.html#RTE_Software_Component_Selection',1,'RTE Component Selection'],['../usbh_create_app.html#RTE_Software_Component_Selection_USBH',1,'RTE Component Selection']]],
  ['components_34',['Components',['../USB_Device.html#usbd_rte_components',1,'RTE Components'],['../USB_Host.html#usbh_rte_components',1,'RTE Components']]],
  ['concepts_35',['USB Concepts',['../USB_Concepts.html',1,'']]],
  ['config_5fdescriptor_5ffs_36',['config_descriptor_fs',['../group__usbd__data__types.html#a4ec10b65bf9ad70010109a4e4b638707',1,'usbd_desc_t']]],
  ['config_5fdescriptor_5fhs_37',['config_descriptor_hs',['../group__usbd__data__types.html#a7f55164ab50a025ae54871f5438e4c3b',1,'usbd_desc_t']]],
  ['configuration_38',['Configuration',['../group__usbd__coreFunctions__conf.html',1,'Configuration'],['../group__usbd__adcFunctions__conf.html',1,'Configuration'],['../group__usbd__cdcFunctions__acm__conf.html',1,'Configuration'],['../group__usbd__cdcFunctions__ncm__conf.html',1,'Configuration'],['../group__usbd__hidFunctions__conf.html',1,'Configuration'],['../group__usbd__mscFunctions__conf.html',1,'Configuration'],['../group__usbd__classFunctions__conf.html',1,'Configuration'],['../group__usbh__coreFunctions__conf.html',1,'Configuration'],['../group__usbh__cdcacmFunctions__conf.html',1,'Configuration'],['../group__usbh__hidFunctions__conf.html',1,'Configuration'],['../group__usbh__mscFunctions__conf.html',1,'Configuration'],['../group__usbh__customFunctions__conf.html',1,'Configuration'],['../usbd_create_app.html#usbDevEvrConfig',1,'Configuration'],['../usbh_create_app.html#usbHostEvrConfig',1,'Configuration'],['../usb_migration.html#usb_migration_config',1,'Configuration'],['../group__usbd__coreFunctions.html#autotoc_md24',1,'Static and Run-Time Configuration'],['../usbd_create_app.html#usbd_system_resources',1,'System Resource Configuration'],['../usbh_create_app.html#usbh_system_resources',1,'System Resource Configuration'],['../usbd_create_app.html#USB_Device_Configuration',1,'USB Device Configuration'],['../usbh_create_app.html#USB_Host_Configuration_USBH',1,'USB Host Configuration']]],
  ['configuration_20and_20usb_20endpoint_20settings_39',['USB Device Class Configuration and USB Endpoint Settings',['../usbd_create_app.html#USB_Device_Class_Configuration',1,'']]],
  ['configuration_20descriptor_40',['Configuration Descriptor',['../USB_Concepts.html#USB_Configuration_Descriptor',1,'']]],
  ['configuration_20of_20attachable_20usb_20devices_41',['Configuration of Attachable USB Devices',['../usbh_create_app.html#USB_Device_Class_Configuration_USBH',1,'']]],
  ['control_20endpoint_200_42',['Control Endpoint 0',['../group__usbd__coreFunctions.html#autotoc_md25',1,'Setup Packets on Control Endpoint 0'],['../group__usbd__classFunctions.html#autotoc_md33',1,'Setup Packets on Control Endpoint 0']]],
  ['control_20model_43',['CDC (ACM): Communication Device Class (Abstract Control Model)',['../group__usbh__cdcacmFunctions.html',1,'']]],
  ['control_20transfers_44',['Control Transfers',['../USB_Concepts.html#USB_Control_Transfers',1,'Control Transfers'],['../USB_Classes.html#CDC_Control_Transfers',1,'Control Transfers'],['../USB_Classes.html#HID_Control_Transfers',1,'Control Transfers'],['../USB_Classes.html#MSC_Control_Transfers',1,'Control Transfers']]],
  ['controller_45',['Controller',['../usbd_create_app.html#USB_Driver_Configuration',1,'USB Driver and Controller'],['../usbh_create_app.html#USB_Driver_Configuration_USBH',1,'USB Driver and Controller']]],
  ['core_46',['Core',['../group__usbd__coreFunctions.html',1,'Core'],['../group__usbh__coreFunctions.html',1,'Core']]],
  ['core_20functions_47',['Core Functions',['../group__usbd__evr__core__func.html',1,'USBD_Core: Core Functions'],['../group__usbh__evr__core__func.html',1,'USBH_Core: Core Functions']]],
  ['create_20an_20application_48',['Create an Application',['../usbd_create_app.html',1,'Create an Application'],['../usbh_create_app.html',1,'Create an Application']]],
  ['custom_20class_49',['Custom Class',['../group__usbd__classFunctions.html',1,'Custom Class'],['../group__usbh__customFunctions.html',1,'Custom Class'],['../USB_Classes.html#CustomClass',1,'Custom Class']]],
  ['custom_20class_20functions_50',['Custom Class Functions',['../group__usbd__evr__cc__func.html',1,'USBD_CustomClass: Custom Class Functions'],['../group__usbh__evr__cc__func.html',1,'USBH_CustomClass: Custom Class Functions']]]
];
