var group__net__evr =
[
    [ "NetSYS: System Core", "group__net__evr__sys__func.html", "group__net__evr__sys__func" ],
    [ "NetMEM: Memory Management", "group__net__evr__mem__func.html", "group__net__evr__mem__func" ],
    [ "NetETH: ETH Interface", "group__net__evr__eth__func.html", "group__net__evr__eth__func" ],
    [ "NetWiFi: WiFi Interface", "group__net__evr__wifi__func.html", "group__net__evr__wifi__func" ],
    [ "NetPPP: PPP Interface", "group__net__evr__ppp__func.html", "group__net__evr__ppp__func" ],
    [ "NetSLIP: SLIP Interface", "group__net__evr__slip__func.html", "group__net__evr__slip__func" ],
    [ "NetLOOP: Loopback Interface", "group__net__evr__loop__func.html", "group__net__evr__loop__func" ],
    [ "NetIP4: IP4 Core", "group__net__evr__ip4__func.html", "group__net__evr__ip4__func" ],
    [ "NetICMP: ICMP Control", "group__net__evr__icmp__func.html", "group__net__evr__icmp__func" ],
    [ "NetIGMP: IGMP Management", "group__net__evr__igmp__func.html", "group__net__evr__igmp__func" ],
    [ "NetNBNS: NBNS Client", "group__net__evr__nbns__func.html", "group__net__evr__nbns__func" ],
    [ "NetDHCP: DHCP Client", "group__net__evr__dhcp__func.html", "group__net__evr__dhcp__func" ],
    [ "NetARP: ARP Address Resolution", "group__net__evr__arp__func.html", "group__net__evr__arp__func" ],
    [ "NetIP6: IP6 Core", "group__net__evr__ip6__func.html", "group__net__evr__ip6__func" ],
    [ "NetICMP6: ICMP6 Control", "group__net__evr__icmp6__func.html", "group__net__evr__icmp6__func" ],
    [ "NetDHCP6: DHCP6 Client", "group__net__evr__dhcp6__func.html", "group__net__evr__dhcp6__func" ],
    [ "NetNDP: NDP Neighbor Discovery", "group__net__evr__ndp__func.html", "group__net__evr__ndp__func" ],
    [ "NetMLD: MLD Multicast Listener Discovery", "group__net__evr__mld__func.html", "group__net__evr__mld__func" ],
    [ "NetUDP: UDP Socket", "group__net__evr__udp__func.html", "group__net__evr__udp__func" ],
    [ "NetTCP: TCP Socket", "group__net__evr__tcp__func.html", "group__net__evr__tcp__func" ],
    [ "NetBSD: BSD Socket", "group__net__evr__bsd__func.html", "group__net__evr__bsd__func" ],
    [ "NetHTTPs: HTTP Server", "group__net__evr__https__func.html", "group__net__evr__https__func" ],
    [ "NetFTPs: FTP Server", "group__net__evr__ftps__func.html", "group__net__evr__ftps__func" ],
    [ "NetFTPc: FTP Client", "group__net__evr__ftpc__func.html", "group__net__evr__ftpc__func" ],
    [ "NetTeln: Telnet Server", "group__net__evr__teln__func.html", "group__net__evr__teln__func" ],
    [ "NetTFTPs: TFTP Server", "group__net__evr__tftps__func.html", "group__net__evr__tftps__func" ],
    [ "NetTFTPc: TFTP Client", "group__net__evr__tftpc__func.html", "group__net__evr__tftpc__func" ],
    [ "NetSMTP: SMTP Client", "group__net__evr__smtp__func.html", "group__net__evr__smtp__func" ],
    [ "NetDNS: DNS Client", "group__net__evr__dns__func.html", "group__net__evr__dns__func" ],
    [ "NetSNMP: SNMP Agent", "group__net__evr__snmp__func.html", "group__net__evr__snmp__func" ],
    [ "NetSNTP: SNTP Client", "group__net__evr__sntp__func.html", "group__net__evr__sntp__func" ]
];