name: Build - USB
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.ci/USB/**'
      - .github/workflows/build_usb.yml
      - 'Examples/USB/**'
      - 'Components/USB/**'
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  examples:
    strategy:
      fail-fast: false
      matrix:
        compiler: [AC6, GCC]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout MDK-Middleware
        uses: actions/checkout@v4
        with:
          path: ./MDK-Middleware

      - name: Cache packs
        uses: actions/cache@v4
        with:
          key: cmsis-packs-${{ hashFiles('**/*.csolution.yml', '**/*.cproject.yml', '**/*.clayer.yml') }}
          restore-keys: |
            cmsis-packs-
          path: /home/runner/.cache/arm/packs

      - name: Prepare vcpkg env
        uses: JonatanAntoni/actions/vcpkg@main
        with:
          config: ./MDK-Middleware/.ci/USB/Device/vcpkg-configuration.json

      - name: Initialize CMSIS pack root folder
        run: |
          cpackget init https://www.keil.com/pack/index.pidx
          cpackget update-index

      - name: Install required CMSIS packs
        working-directory: ./MDK-Middleware/.ci/USB/
        run: |
          # Create list of used packs - keep pack specification only (remove path/URL)
          csolution list packs ./Device/USB_Device.csolution.yml | sed 's/ .*//' > packs_usbd.txt
          csolution list packs ./Host/USB_Host.csolution.yml | sed 's/ .*//' > packs_usbh.txt
          # Remove MDK-Middleware from the list
          sed -i '/.*MDK-Middleware.*/d' packs_usbd.txt
          sed -i '/.*MDK-Middleware.*/d' packs_usbh.txt
          # Keep only leters, numbers, ':', '@', '.', '_' and '-'
          sed -i 's/[^a-zA-Z0-9:@._-]//g' packs_usbd.txt
          sed -i 's/[^a-zA-Z0-9:@._-]//g' packs_usbh.txt
          # Install required packs
          cpackget add -a -n -f packs_usbd.txt
          cpackget add -a -n -f packs_usbh.txt

      - name: Use local MDK-Middleware pack
        working-directory: ./MDK-Middleware/
        run: |
          cpackget rm Keil.MDK-Middleware || true
          cpackget add ./Keil.MDK-Middleware.pdsc

      - name: Activate Arm tool license
        run: |
          armlm activate --server https://mdk-preview.keil.arm.com --product KEMDK-COM0

      - uses: ammaraskar/gcc-problem-matcher@master

      - name: Build USB Device sources
        working-directory: ./MDK-Middleware/.ci/USB/Device
        run: |
          cbuild USB_Device.csolution.yml --update-rte --toolchain ${{ matrix.compiler }} 2>&1 | tee build_usbd_${{ matrix.compiler }}.log || true

      - name: Build USB Host sources
        working-directory: ./MDK-Middleware/.ci/USB/Host
        run: |
          cbuild USB_Host.csolution.yml --update-rte --toolchain ${{ matrix.compiler }} 2>&1 | tee build_usbh_${{ matrix.compiler }}.log || true

      - name: Create build summary
        working-directory: ./MDK-Middleware/.ci/USB
        run: |
          # Parse build log:
          # 1. keep only lines that contain text:
          #    - "Building context:" or
          #    - "error csolution:" or
          #    - "error cbuild: error building" or
          #    - "error cbuild: exit status" or
          #    - "cbuild: build finished"
          # 2. replace all lines that contain text "error cbuild" with word "ERROR"
          # 3. replace all lines that contain text "successfully" with word "OK"
          # 4. to all lines that contain text "info", append the next line
          sed -n '/Building context:\|error csolution:\|error cbuild: error building\|error cbuild: exit status\|cbuild: build finished/p' ./Device/build_usbd_${{ matrix.compiler }}.log | sed '/error cbuild/s/.*/ERROR/' | sed '/successfully/s/.*/OK/' | sed '/info/ {N;s/\n/ /}' 2>&1 | tee summary_usbd_${{ matrix.compiler }}.log
          sed -n '/Building context:\|error csolution:\|error cbuild: error building\|error cbuild: exit status\|cbuild: build finished/p' ./Host/build_usbh_${{ matrix.compiler }}.log | sed '/error cbuild/s/.*/ERROR/' | sed '/successfully/s/.*/OK/' | sed '/info/ {N;s/\n/ /}' 2>&1 | tee summary_usbh_${{ matrix.compiler }}.log

          # Return error if text "ERROR" is found in the summary
          awk '/ERROR/{print "Build FAILED."; exit 1}' summary_usbd_${{ matrix.compiler }}.log
          awk '/ERROR/{print "Build FAILED."; exit 1}' summary_usbh_${{ matrix.compiler }}.log

      - name: Deactivate Arm tool license
        if: always()
        run: |
          armlm deactivate --product KEMDK-COM0
